import { ArrowLeft, Shield, Users, CreditCard, Activity, Ban, AlertTriangle, FileText, RefreshCw } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';

const sections = [
  {
    icon: Shield,
    title: '1. Acceptance of Terms',
    content: 'By accessing or using the Success Desirous Student Management System, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use this system.',
  },
  {
    icon: Users,
    title: '2. Authorized Access Only',
    content: `Only approved staff members are permitted to access this system. Newly registered users will remain in a "Pending Approval" state until activated by an Administrator. The Admin reserves the right to suspend or revoke any user's access at any time, without prior notice.`,
  },
  {
    icon: FileText,
    title: '3. Data Responsibility',
    content: 'Staff members are solely responsible for the accuracy of student information they enter, including name, contact details, fees, and admission dates. All student data is stored strictly for institute management purposes and will not be shared with any third party.',
  },
  {
    icon: CreditCard,
    title: '4. Fee Policy',
    content: 'The monthly fee schedule generated by the system is considered final. Fees are automatically calculated based on enrollment date and course duration. No manual override is permitted without explicit Admin approval. In the event of any payment dispute, system-generated records will serve as the primary evidence.',
  },
  {
    icon: Activity,
    title: '5. Activity Monitoring & Audit Logs',
    content: 'Users acknowledge that all activity within this system is logged, including login/logout timestamps, additions, edits, or deletions to student records, and payment status updates. These logs exist for transparency and accountability and may be reviewed by the Administrator at any time.',
  },
  {
    icon: Ban,
    title: '6. Prohibited Actions',
    content: 'The following actions are strictly prohibited: Using another user\'s login credentials, exporting student data for unauthorized purposes, attempting to bypass or circumvent any security feature, and entering false or fabricated student information.',
  },
  {
    icon: AlertTriangle,
    title: '7. Termination',
    content: 'The Administrator may immediately disable any user account upon violation of these Terms, without obligation to provide a reason.',
  },
  {
    icon: Shield,
    title: '8. Limitation of Liability',
    content: 'Success Desirous shall not be held liable for any technical errors, data loss, or system downtime. Users are encouraged to maintain regular data backups via the export feature provided within the system.',
  },
  {
    icon: RefreshCw,
    title: '9. Changes to Terms',
    content: 'These Terms may be updated at any time. Users will be notified of any significant changes. Continued use of the system following an update constitutes acceptance of the revised Terms.',
  },
];

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-950 to-violet-950 text-white">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-black/30 backdrop-blur-xl border-b border-white/10">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center gap-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate(-1)}
            className="text-white/70 hover:text-white hover:bg-white/10 rounded-full"
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div>
            <h1 className="text-lg font-bold">Terms & Conditions</h1>
            <p className="text-xs text-white/50">Last updated: March 2026</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
        <div className="bg-white/5 backdrop-blur-sm rounded-2xl border border-white/10 p-6 mb-8">
          <p className="text-white/70 text-sm leading-relaxed">
            Welcome to the <span className="text-white font-semibold">Success Desirous Student Management System</span>. 
            Please read these terms carefully before using the platform. By registering and creating an account, 
            you confirm that you have read, understood, and accepted these terms in full.
          </p>
        </div>

        {sections.map((section, i) => (
          <div
            key={i}
            className="bg-white/5 backdrop-blur-sm rounded-2xl border border-white/10 p-5 sm:p-6 hover:bg-white/[0.07] transition-colors"
          >
            <div className="flex items-start gap-3 mb-3">
              <div className="p-2 rounded-lg bg-primary/20 text-primary shrink-0 mt-0.5">
                <section.icon className="w-4 h-4" />
              </div>
              <h2 className="text-base sm:text-lg font-semibold">{section.title}</h2>
            </div>
            <p className="text-white/60 text-sm leading-relaxed pl-11">{section.content}</p>
          </div>
        ))}

        <div className="text-center pt-6 pb-12">
          <p className="text-white/40 text-xs">
            © {new Date().getFullYear()} Success Desirous. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
